export const GET_MOVIE_REQUEST = "GET_MOVIE_REQUEST";
export const GET_MOVIE_SUCCESS = "GET_MOVIE_SUCCESS";
export const GET_MOVIE_FAILED = "GET_MOVIE_FAILED";

export const GET_MOVIE_BY_ID_REQUEST = "GET_MOVIE_BY_ID_REQUEST";
export const GET_MOVIE_BY_ID_SUCCESS = "GET_MOVIE_BY_ID_SUCCESS";
export const GET_MOVIE_BY_ID_FAILED = "GET_MOVIE_BY_ID_FAILED";

export const GET_MOVIE_TYPE_REQUEST = "GET_MOVIE_TYPE_REQUEST";
export const GET_MOVIE_TYPE_SUCCESS = "GET_MOVIE_TYPE_SUCCESS";
export const GET_MOVIE_TYPE_FAILED = "GET_MOVIE_TYPE_FAILED";
